FROM oven/bun:1.3.1-alpine

WORKDIR /app

# copy package first to leverage Docker layer cache
COPY package.json ./

RUN bun install

COPY . .

ENV VITE_HOST=http://143.110.226.0:4456

RUN bun run build

# EXPOSE 5173

# Ensure the process binds to 0.0.0.0 so the port is reachable from the host
CMD ["bun", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]